version: '3.4'

services: 
  webapi:
    container_name: WebAPI
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/API/Dockerfile
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost:7001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwe123asd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
    ports:
      - 7001:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - sqlserver
  sqlserver:
    container_name: SQLSERVER2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=Sql123123..
    ports:
     - 1433:1433 
    volumes:
      - /var/opt/mssql/data
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 10s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Sql123123.. -d master -Q 'CREATE DATABASE [WebAPI]' && sleep infinity"
    restart: always
  


  
    
